# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
mod_name=Dynamic Trees - Still Life
mod_author=Wexit
mod_id=dtstilllife
mod_description=Still Life support for Dynamic Trees
mod_license=None
mod_credits=Wexit
mod_authors=Wexit
mod_group_id=wexlabs
version=1.0.0
neoVersionAppend=
versionType=stable
mod_url=None

# Common
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_form_version=1.21.1-20240808.144430
java_version=21

# NeoForge
neoforge_version=21.1.208
neoforge_loader_version_range=[4,)

dynamic_trees_version=1.7.1
dynamic_trees_plus_version=1.3.2

still_life_version=1

vanilla_backport_version_id=8115367

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
forge_config_api_port_version=21.1.6


